# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_hospital_expense_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='hospital',
        ),
    ]
