# Generated by Django 4.2.7 on 2026-03-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0010_patientgroup_patient_patient_group'),
        ('billing', '0002_alter_payment_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this service for this patient group', max_digits=10)),
                ('patient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='patients.patientgroup')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='appointments.service')),
            ],
            options={
                'verbose_name': 'Service Group Price',
                'verbose_name_plural': 'Service Group Prices',
                'ordering': ['service', 'patient_group'],
                'unique_together': {('service', 'patient_group')},
            },
        ),
    ]
