# Generated by Django 4.2.7 on 2026-03-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_labtestpricegroup'),
        ('appointments', '0001_initial'),
        ('billing', '0003_servicepricegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='laboratory.labtestrequest'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.service'),
        ),
    ]
