# Generated by Django 4.2.7 on 2026-03-05 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_invoicelineitem_lab_test_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_status_changed', 'Invoice Status Changed'), ('invoice_emailed', 'Invoice Emailed'), ('payment_created', 'Payment Created'), ('payment_refunded', 'Payment Refunded'), ('payment_status_changed', 'Payment Status Changed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='billing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='billing.payment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Audit Log',
                'verbose_name_plural': 'Billing Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
