# Generated by Django 4.2.7 on 2026-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billing_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for published invoice PDF'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for published receipt PDF'),
        ),
    ]
