# Generated by Django 4.2.7 on 2026-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_pdf_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gdrive_pdf_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for published invoice PDF'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gdrive_pdf_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for published receipt PDF'),
        ),
    ]
