# Generated by Django 4.2.7 on 2026-03-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0015_alter_vitalsigns_blood_pressure_diastolic_and_more'),
        ('appointments', '0001_initial'),
        ('laboratory', '0014_testcategory_alter_labtest_category_and_more'),
        ('billing', '0007_gdrive_pdf_url_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('auto', 'Auto-Generated (Period)'), ('custom', 'Custom Invoice')], default='auto', max_length=10)),
                ('period_start', models.DateField(blank=True, help_text='Start date for services included', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date for services included', null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('billing_contact_name', models.CharField(blank=True, max_length=200)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('billing_contact_phone', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('invoice_pdf_url', models.URLField(blank=True)),
                ('gdrive_pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invoices', to='patients.patientgroup')),
            ],
            options={
                'verbose_name': 'Group Invoice',
                'verbose_name_plural': 'Group Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer'), ('credit_card', 'Credit Card')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('receipt_pdf_url', models.URLField(blank=True)),
                ('gdrive_pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_payments', to='billing.groupinvoice')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Payment',
                'verbose_name_plural': 'Group Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('group_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.groupinvoice')),
                ('lab_test_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labtestrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invoice_items', to='patients.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.service')),
            ],
            options={
                'verbose_name': 'Group Invoice Item',
                'verbose_name_plural': 'Group Invoice Items',
                'ordering': ['service_date', 'patient'],
            },
        ),
    ]
