# Generated by Django 4.2.7 on 2026-03-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_vitalsigns_blood_pressure_diastolic_and_more'),
        ('billing', '0008_groupinvoice_grouppayment_groupinvoiceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinvoiceitem',
            options={'ordering': ['service_date', 'id'], 'verbose_name': 'Group Invoice Item', 'verbose_name_plural': 'Group Invoice Items'},
        ),
        migrations.AlterField(
            model_name='groupinvoiceitem',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_invoice_items', to='patients.patient'),
        ),
    ]
