# Generated by Django 4.2.7 on 2026-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('billing', '0009_alter_groupinvoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvoice',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_invoices', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.hospital'),
        ),
    ]
