# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_groupinvoice_hospital_invoice_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvoice',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='hospital',
        ),
    ]
