# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicalrecord_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='hospital',
        ),
    ]
