# Generated by Django 4.2.7 on 2025-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
    ]
