# Generated by Django 4.2.7 on 2025-10-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_assessment_diagnosis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0002_alter_labtest_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name'], 'verbose_name': 'Laboratory Test', 'verbose_name_plural': 'Laboratory Tests'},
        ),
        migrations.AlterModelOptions(
            name='labtestrequest',
            options={'ordering': ['-date_requested'], 'verbose_name': 'Lab Test Request', 'verbose_name_plural': 'Lab Test Requests'},
        ),
        migrations.AlterModelOptions(
            name='labtestresult',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Lab Test Result', 'verbose_name_plural': 'Lab Test Results'},
        ),
        migrations.RemoveField(
            model_name='labtestresult',
            name='result',
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology'), ('immunology', 'Immunology'), ('pathology', 'Pathology'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='duration_hours',
            field=models.IntegerField(default=24, help_text='Expected turnaround time in hours'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_range',
            field=models.CharField(blank=True, help_text='Normal reference range', max_length=200),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, help_text='e.g., Blood, Urine, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Clinical indication for test'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='interpretation',
            field=models.TextField(blank=True, help_text='Clinical interpretation'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='result_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='result_value',
            field=models.TextField(default=1, help_text='Test result value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='code',
            field=models.CharField(help_text='Unique test code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='laboratory.labtest'),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labtestrequest'),
        ),
    ]
