# Generated by Django 4.2.7 on 2026-02-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_labtest_options_alter_labtestrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Parameter code for reporting', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('result_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('positive_negative', 'Positive/Negative'), ('reactive_nonreactive', 'Reactive/Non-reactive'), ('present_absent', 'Present/Absent'), ('detected_not_detected', 'Detected/Not Detected'), ('normal_abnormal', 'Normal/Abnormal'), ('yes_no', 'Yes/No'), ('grade', 'Grade (1+, 2+, 3+, 4+)'), ('titer', 'Titer'), ('percentage', 'Percentage'), ('ratio', 'Ratio'), ('custom', 'Custom Options')], default='numeric', max_length=25)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range_min', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('reference_range_max', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('reference_range_text', models.CharField(blank=True, max_length=200)),
                ('flag_criteria', models.CharField(choices=[('none', 'No Flagging'), ('range', 'Reference Range'), ('positive_negative', 'Positive/Negative'), ('reactive_nonreactive', 'Reactive/Non-reactive'), ('present_absent', 'Present/Absent'), ('detected_not_detected', 'Detected/Not Detected'), ('normal_abnormal', 'Normal/Abnormal'), ('custom', 'Custom Logic')], default='range', max_length=25)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('custom_options', models.JSONField(blank=True, default=dict, help_text='Custom options for result types')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Parameter',
                'verbose_name_plural': 'Test Parameters',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique profile code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology'), ('immunology', 'Immunology'), ('pathology', 'Pathology'), ('other', 'Other')], default='other', max_length=20)),
                ('sample_type', models.CharField(blank=True, help_text='e.g., Blood, Urine, etc.', max_length=100)),
                ('duration_hours', models.IntegerField(default=24, help_text='Expected turnaround time in hours')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Profile',
                'verbose_name_plural': 'Test Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(choices=[('simple', 'Simple Test'), ('profile', 'Test Profile')], default='simple', max_length=10),
        ),
        migrations.CreateModel(
            name='TestProfileParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.testparameter')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.testprofile')),
            ],
            options={
                'verbose_name': 'Profile Parameter',
                'verbose_name_plural': 'Profile Parameters',
                'ordering': ['display_order'],
                'unique_together': {('profile', 'parameter')},
            },
        ),
        migrations.AddField(
            model_name='testprofile',
            name='parameters',
            field=models.ManyToManyField(through='laboratory.TestProfileParameter', to='laboratory.testparameter'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='laboratory.testprofile'),
        ),
        migrations.CreateModel(
            name='ParameterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=500)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critical Low'), ('critical_high', 'Critical High'), ('abnormal', 'Abnormal'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.testparameter')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_results', to='laboratory.labtestresult')),
            ],
            options={
                'verbose_name': 'Parameter Result',
                'verbose_name_plural': 'Parameter Results',
                'ordering': ['parameter__display_order', 'parameter__name'],
                'unique_together': {('test_result', 'parameter')},
            },
        ),
    ]
