# Generated by Django 4.2.7 on 2026-03-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_testparameter_testprofile_labtest_test_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='test_type',
        ),
    ]
