# Generated by Django 4.2.7 on 2026-03-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientgroup_patient_patient_group'),
        ('laboratory', '0005_remove_test_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestPriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this lab test for this patient group', max_digits=10)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='laboratory.labtest')),
                ('patient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_prices', to='patients.patientgroup')),
            ],
            options={
                'verbose_name': 'Lab Test Price Group',
                'verbose_name_plural': 'Lab Test Price Groups',
                'unique_together': {('lab_test', 'patient_group')},
            },
        ),
    ]
