# Generated by Django 4.2.7 on 2026-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_labtestpricegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='reason_for_test',
            field=models.TextField(blank=True, help_text='Reason/indication for requesting this test'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='samples_required',
            field=models.CharField(blank=True, help_text='Sample types required (e.g., Blood, Urine, Stool)', max_length=200),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Additional clinical notes'),
        ),
    ]
