# Generated by Django 4.2.7 on 2026-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labtestrequest_reason_for_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameter',
            name='category',
            field=models.CharField(choices=[('physical', 'Physical Examination'), ('chemical', 'Chemical Examination'), ('microscopic', 'Microscopic Examination')], default='chemical', help_text='Parameter examination category', max_length=20),
        ),
    ]
