# Generated by Django 4.2.7 on 2026-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_testparameter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='certificate_pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for published certificate PDF'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='report_pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for published report PDF'),
        ),
    ]
