# Generated by Django 4.2.7 on 2026-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_add_cloud_pdf_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='certificate_gdrive_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for published certificate PDF'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='report_gdrive_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for published report PDF'),
        ),
    ]
