# Generated by Django 4.2.7 on 2026-03-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_gdrive_pdf_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameter',
            name='category',
            field=models.CharField(blank=True, choices=[('physical', 'Physical Examination'), ('chemical', 'Chemical Examination'), ('microscopic', 'Microscopic Examination')], default='', help_text='Parameter examination category', max_length=20),
        ),
    ]
