# Generated by Django 4.2.7 on 2026-03-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_allow_blank_parameter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameter',
            name='category',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('physical', 'Physical Examination'), ('chemical', 'Chemical Examination'), ('microscopic', 'Microscopic Examination')], default='', help_text='Parameter examination category', max_length=20),
        ),
    ]
