# Generated by Django 4.2.7 on 2026-03-08 17:07

from django.db import migrations, models
import django.db.models.deletion


def create_categories_and_migrate(apps, schema_editor):
    """Create categories and migrate existing parameters"""
    ParameterCategory = apps.get_model('laboratory', 'ParameterCategory')
    TestParameter = apps.get_model('laboratory', 'TestParameter')
    
    # Create default categories
    categories = [
        ('physical', 'Physical Examination', 1),
        ('chemical', 'Chemical Examination', 2),
        ('microscopic', 'Microscopic Examination', 3),
        ('none', 'None', 4),
    ]
    
    category_map = {}
    for code, name, order in categories:
        category, created = ParameterCategory.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'display_order': order,
                'is_active': True
            }
        )
        category_map[code] = category
    
    # First, set all parameters to 'none' category
    TestParameter.objects.update(category=category_map['none'])
    
    # Update parameters based on naming patterns
    physical_keywords = ['color', 'appearance', 'clarity', 'transparency', 'odor']
    chemical_keywords = ['glucose', 'protein', 'ketones', 'blood', 'ph', 'nitrite', 'leukocytes', 'bilirubin', 'urobilinogen']
    microscopic_keywords = ['cells', 'casts', 'crystals', 'bacteria', 'yeast', 'parasites', 'mucus']
    
    for param in TestParameter.objects.all():
        name_lower = param.name.lower()
        code_lower = param.code.lower() if param.code else ''
        
        if any(keyword in name_lower or keyword in code_lower for keyword in physical_keywords):
            param.category = category_map['physical']
        elif any(keyword in name_lower or keyword in code_lower for keyword in chemical_keywords):
            param.category = category_map['chemical']
        elif any(keyword in name_lower or keyword in code_lower for keyword in microscopic_keywords):
            param.category = category_map['microscopic']
        else:
            param.category = category_map['none']
        
        param.save()


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_alter_testparameter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='Category code for templates', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Category',
                'verbose_name_plural': 'Parameter Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='laboratory.parametercategory'),
        ),
        migrations.RunPython(create_categories_and_migrate),
    ]
