# Generated by Django 4.2.7 on 2026-03-08 17:09

from django.db import migrations, models
import django.db.models.deletion


def create_test_categories_and_migrate(apps, schema_editor):
    """Create test categories and migrate existing lab tests and profiles"""
    TestCategory = apps.get_model('laboratory', 'TestCategory')
    LabTest = apps.get_model('laboratory', 'LabTest')
    TestProfile = apps.get_model('laboratory', 'TestProfile')
    
    # Create default test categories
    categories = [
        ('hematology', 'Hematology', 1),
        ('biochemistry', 'Biochemistry', 2),
        ('microbiology', 'Microbiology', 3),
        ('serology', 'Serology', 4),
        ('immunology', 'Immunology', 5),
        ('pathology', 'Pathology', 6),
        ('other', 'Other', 7),
    ]
    
    category_map = {}
    for code, name, order in categories:
        category, created = TestCategory.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'display_order': order,
                'is_active': True
            }
        )
        category_map[code] = category
    
    # Since we can't access the old string values after the field change,
    # we'll set all existing records to 'other' category
    # Users can manually update them in the admin if needed
    LabTest.objects.update(category=category_map['other'])
    TestProfile.objects.update(category=category_map['other'])


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_parametercategory_alter_testparameter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='Category code for templates', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Category',
                'verbose_name_plural': 'Test Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='laboratory.testcategory'),
        ),
        migrations.AlterField(
            model_name='testprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_profiles', to='laboratory.testcategory'),
        ),
        migrations.RunPython(create_test_categories_and_migrate),
    ]
