# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_labtestrequest_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequest',
            name='hospital',
        ),
    ]
