# Generated by Django 4.2.7 on 2026-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person name', max_length=150),
        ),
        migrations.AddField(
            model_name='hospital',
            name='max_patients',
            field=models.PositiveIntegerField(default=500, help_text='Maximum number of patients allowed'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='max_users',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of staff users allowed'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes about this hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
    ]
