# Generated by Django 5.2.7 on 2025-10-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_category_supplier_batch_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='quantity',
            new_name='quantity_remaining',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='description',
            new_name='notes',
        ),
    ]
