# Generated by Django 4.2.7 on 2025-11-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medication'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.category'),
        ),
    ]
