# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_prescription_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='hospital',
        ),
    ]
