# Generated by Django 4.2.20 on 2026-04-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_remove_prescription_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='e.g., Tablet, Strip, Bottle, Sachet', max_length=50)),
                ('quantity_per_base', models.PositiveIntegerField(default=1, help_text='How many of this unit are in the base unit (e.g., 10 strips per box)')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price for this unit', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default selling unit?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pharmacy.medication')),
            ],
            options={
                'ordering': ['-is_default', 'unit_name'],
                'unique_together': {('medication', 'unit_name')},
            },
        ),
    ]
