# Generated by Django 5.0.6 on 2025-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Alafia Point Wellness Clinic', help_text='The name of your clinic', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Upload your clinic logo (recommended size: 200x80px)', null=True, upload_to='clinic_logos/')),
                ('address', models.TextField(blank=True, help_text='Clinic address')),
                ('phone', models.CharField(blank=True, help_text='Clinic phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Clinic email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Clinic website URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
    ]
