# Generated by Django 4.2.7 on 2025-10-22 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='accent_color',
            field=models.CharField(default='#00A86B', help_text='Accent/highlight color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='accent_dark',
            field=models.CharField(default='#008554', help_text='Dark variant of accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='accent_light',
            field=models.CharField(default='#e6f9f3', help_text='Light variant of accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='bg_primary',
            field=models.CharField(default='#ffffff', help_text='Primary background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='bg_secondary',
            field=models.CharField(default='#f8fafc', help_text='Secondary background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='bg_tertiary',
            field=models.CharField(default='#f1f5f9', help_text='Tertiary background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='border_color',
            field=models.CharField(default='#e2e8f0', help_text='Border color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='chart_color_1',
            field=models.CharField(default='#1B5E96', help_text='Chart color 1', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='chart_color_2',
            field=models.CharField(default='#2E8B57', help_text='Chart color 2', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='chart_color_3',
            field=models.CharField(default='#00A86B', help_text='Chart color 3', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='chart_color_4',
            field=models.CharField(default='#FF8C00', help_text='Chart color 4', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='chart_color_5',
            field=models.CharField(default='#0891b2', help_text='Chart color 5', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='chart_color_6',
            field=models.CharField(default='#dc2626', help_text='Chart color 6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='danger_color',
            field=models.CharField(default='#dc2626', help_text='Danger/error color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='danger_dark',
            field=models.CharField(default='#b91c1c', help_text='Dark variant of danger color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='danger_light',
            field=models.CharField(default='#fecaca', help_text='Light variant of danger color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='dark_color',
            field=models.CharField(default='#1e293b', help_text='Dark text/background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='info_color',
            field=models.CharField(default='#0891b2', help_text='Info/informational color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='info_dark',
            field=models.CharField(default='#0e7490', help_text='Dark variant of info color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='info_light',
            field=models.CharField(default='#cffafe', help_text='Light variant of info color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='light_color',
            field=models.CharField(default='#f8fafc', help_text='Light background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='primary_color',
            field=models.CharField(default='#1B5E96', help_text='Primary brand color (default: #1B5E96)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='primary_dark',
            field=models.CharField(default='#154a7a', help_text='Dark variant of primary color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='primary_light',
            field=models.CharField(default='#e6f1fa', help_text='Light variant of primary color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='secondary_color',
            field=models.CharField(default='#64748b', help_text='Secondary/neutral color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='secondary_dark',
            field=models.CharField(default='#475569', help_text='Dark variant of secondary color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='secondary_light',
            field=models.CharField(default='#f1f5f9', help_text='Light variant of secondary color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='success_color',
            field=models.CharField(default='#2E8B57', help_text='Success/positive action color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='success_dark',
            field=models.CharField(default='#236b43', help_text='Dark variant of success color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='success_light',
            field=models.CharField(default='#e8f5f0', help_text='Light variant of success color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='text_muted',
            field=models.CharField(default='#94a3b8', help_text='Muted text color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='text_primary',
            field=models.CharField(default='#1e293b', help_text='Primary text color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='text_secondary',
            field=models.CharField(default='#64748b', help_text='Secondary text color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='warning_color',
            field=models.CharField(default='#FF8C00', help_text='Warning/caution color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='warning_dark',
            field=models.CharField(default='#e67e00', help_text='Dark variant of warning color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='warning_light',
            field=models.CharField(default='#fff4e6', help_text='Light variant of warning color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1B5E96)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
