# Generated by Django 4.2.7 on 2026-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0002_clinicsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnabledModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('patients', 'Patients Management'), ('appointments', 'Appointments'), ('medical_records', 'Medical Records'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('budget', 'Budget & Expenses'), ('staff_management', 'Staff Management'), ('reports', 'Reports')], help_text='System module identifier', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the module', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this module is enabled and visible in the system')),
                ('icon', models.CharField(default='bi bi-box', help_text='Bootstrap icon class for the module', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enabled Module',
                'verbose_name_plural': 'Enabled Modules',
                'ordering': ['order', 'display_name'],
            },
        ),
    ]
