# Generated by Django 4.2.7 on 2026-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0003_enabledmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='box_number',
            field=models.CharField(blank=True, help_text='P.O. Box number (e.g., P.O.Box 200210, Kampala - Uganda)', max_length=100),
        ),
    ]
