# Generated by Django 4.2.7 on 2026-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0004_clinicsettings_box_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='postal_address',
            field=models.TextField(blank=True, help_text='Postal address (street address for mail delivery)'),
        ),
    ]
