# Generated by Django 4.2.7 on 2026-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('clinic_settings', '0005_clinicsettings_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_settings', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='enabledmodule',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enabled_modules', to='tenants.hospital'),
        ),
        migrations.AlterField(
            model_name='enabledmodule',
            name='module_name',
            field=models.CharField(choices=[('patients', 'Patients Management'), ('appointments', 'Appointments'), ('medical_records', 'Medical Records'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('budget', 'Budget & Expenses'), ('staff_management', 'Staff Management'), ('reports', 'Reports')], help_text='System module identifier', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='enabledmodule',
            unique_together={('hospital', 'module_name')},
        ),
    ]
