# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0006_clinicsettings_hospital_enabledmodule_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsettings',
            name='hospital',
        ),
    ]
