# Generated by Django 4.2.7 on 2025-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('clinic_manager', 'Clinic Manager'), ('medical_director', 'Medical Director'), ('doctor', 'Doctor/General Practitioner'), ('physiotherapist', 'Physiotherapist'), ('nutritionist', 'Nutritionist/Dietitian'), ('nurse', 'Nurse'), ('clinical_assistant', 'Clinical Assistant'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk Officer'), ('appointment_coordinator', 'Appointment Coordinator'), ('lab_technician', 'Laboratory Technician'), ('lab_manager', 'Laboratory Manager'), ('pathologist', 'Pathologist'), ('pharmacist', 'Pharmacist'), ('pharmacy_assistant', 'Pharmacy Assistant'), ('pharmacy_manager', 'Pharmacy Manager'), ('billing_officer', 'Billing Officer'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('cashier', 'Cashier'), ('medical_records_officer', 'Medical Records Officer'), ('records_manager', 'Records Manager'), ('data_entry_clerk', 'Data Entry Clerk'), ('reports_analyst', 'Reports Analyst'), ('statistician', 'Statistician'), ('hr_manager', 'HR Manager'), ('hr_officer', 'HR Officer'), ('budget_officer', 'Budget Officer'), ('financial_controller', 'Financial Controller'), ('it_support', 'IT Support'), ('maintenance_staff', 'Maintenance Staff')], default='receptionist', max_length=50),
        ),
    ]
