# Generated by Django 4.2.7 on 2026-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='The hospital this user belongs to. Superusers may have no hospital.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.hospital'),
        ),
    ]
