# Generated by Django 4.2.7 on 2026-03-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('patients', 'Patients'), ('appointments', 'Appointments'), ('billing', 'Billing & Finance'), ('medical_records', 'Medical Records'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('reports', 'Reports & Analytics'), ('staff_management', 'Staff Management'), ('budget', 'Budget & Planning'), ('clinic_settings', 'Clinic Settings')], max_length=50)),
                ('is_allowed', models.BooleanField(default=True, help_text='If checked, user CAN access this app. If unchecked, user is BLOCKED.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Permission',
                'verbose_name_plural': 'User App Permissions',
                'ordering': ['user', 'app_name'],
                'unique_together': {('user', 'app_name')},
            },
        ),
    ]
