# Generated by Django 4.2.20 on 2026-03-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_hospital'),
        ('accounts', '0004_remove_user_hospital_userapppermission'),
    ]

    operations = [
    ]
