# Generated by Django 4.2.20 on 2026-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260330_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administration & Management', [('admin', 'System Administrator'), ('clinic_manager', 'Clinic Manager'), ('medical_director', 'Medical Director')]), ('Clinical Staff', [('doctor', 'Doctor/General Practitioner'), ('physiotherapist', 'Physiotherapist'), ('nutritionist', 'Nutritionist/Dietitian'), ('nurse', 'Nurse'), ('clinical_assistant', 'Clinical Assistant')]), ('Reception & Front Desk', [('receptionist', 'Receptionist'), ('front_desk', 'Front Desk Officer'), ('appointment_coordinator', 'Appointment Coordinator')]), ('Laboratory', [('lab_technician', 'Laboratory Technician'), ('lab_manager', 'Laboratory Manager'), ('pathologist', 'Pathologist')]), ('Pharmacy', [('pharmacist', 'Pharmacist'), ('pharmacy_assistant', 'Pharmacy Assistant'), ('pharmacy_manager', 'Pharmacy Manager')]), ('Billing & Finance', [('billing_officer', 'Billing Officer'), ('accountant', 'Accountant'), ('finance_manager', 'Finance Manager'), ('cashier', 'Cashier')]), ('Medical Records', [('medical_records_officer', 'Medical Records Officer'), ('records_manager', 'Records Manager'), ('data_entry_clerk', 'Data Entry Clerk')]), ('Reports & Analytics', [('reports_analyst', 'Reports Analyst'), ('statistician', 'Statistician')]), ('Staff Management', [('hr_manager', 'HR Manager'), ('hr_officer', 'HR Officer')]), ('Budget & Financial Planning', [('budget_officer', 'Budget Officer'), ('financial_controller', 'Financial Controller')]), ('Support & Maintenance', [('it_support', 'IT Support'), ('maintenance_staff', 'Maintenance Staff')])], default='receptionist', max_length=50),
        ),
    ]
