# Generated by Django 4.2.7 on 2025-10-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cashflow',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='drug',
            name='atc_code',
            field=models.CharField(blank=True, help_text='WHO ATC code', max_length=20),
        ),
        migrations.AddField(
            model_name='drug',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drug',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drugusage',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drugusage',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='drugusage',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drugusage',
            name='sold_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drugusage',
            name='usage_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('sale', 'Sale')], default='internal', max_length=10),
        ),
        migrations.AlterField(
            model_name='drugusage',
            name='used_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drugusage',
            name='used_for',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
