# Generated by Django 4.2.7 on 2025-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_cashflow_country_cashflow_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AlterField(
            model_name='drug',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AlterField(
            model_name='drugusage',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
    ]
