# Generated by Django 5.0.6 on 2025-09-10 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('nutrition', 'Nutrition'), ('consultation', 'Consultation'), ('assessment', 'Assessment'), ('treatment', 'Treatment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Appointment notes or special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_provider', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.service')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'unique_together': {('provider', 'appointment_date', 'appointment_time')},
            },
        ),
        migrations.CreateModel(
            name='NutritionConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_diet', models.TextField(help_text='Current dietary habits')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Allergies, intolerances, preferences')),
                ('health_goals', models.TextField(help_text="Patient's health and nutrition goals")),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('meal_plan', models.TextField(help_text='Recommended meal plan')),
                ('supplements', models.TextField(blank=True, help_text='Recommended supplements')),
                ('lifestyle_recommendations', models.TextField(blank=True, help_text='Lifestyle and activity recommendations')),
                ('follow_up_weeks', models.IntegerField(default=4, help_text='Recommended follow-up in weeks')),
                ('consultation_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_consultation', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-appointment__appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='Main reason for visit')),
                ('assessment_findings', models.TextField(help_text='Clinical assessment findings')),
                ('treatment_provided', models.TextField(help_text='Treatment/interventions provided')),
                ('patient_response', models.TextField(help_text="Patient's response to treatment")),
                ('pain_level_before', models.IntegerField(blank=True, help_text='Pain scale 0-10 before treatment', null=True)),
                ('pain_level_after', models.IntegerField(blank=True, help_text='Pain scale 0-10 after treatment', null=True)),
                ('functional_improvement', models.TextField(blank=True, help_text='Functional improvements noted')),
                ('home_exercises', models.TextField(blank=True, help_text='Prescribed home exercises')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations and advice')),
                ('next_appointment_notes', models.TextField(blank=True, help_text='Notes for next appointment')),
                ('session_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_session', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-appointment__appointment_date'],
            },
        ),
    ]
