# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
    ]
