# Generated by Django 4.2.7 on 2026-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.hospital'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short code for department', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'name'), ('hospital', 'code')},
        ),
    ]
