# Generated by Django 5.0.6 on 2025-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageassessment',
            name='assigned_department',
            field=models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('nutrition', 'Nutrition'), ('general', 'General Medicine')], default='general', max_length=20),
        ),
    ]
