# Generated by Django 5.0.6 on 2025-09-15 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_triageassessment_assigned_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_department', models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('nutrition', 'Nutrition'), ('general', 'General Medicine')], default='general', max_length=20)),
                ('chief_complaint', models.TextField(help_text='Primary reason for visit')),
                ('pain_scale', models.IntegerField(blank=True, help_text='Pain scale 0-10', null=True)),
                ('priority_level', models.CharField(choices=[('1', 'Critical - Immediate'), ('2', 'High - Within 15 minutes'), ('3', 'Medium - Within 30 minutes'), ('4', 'Low - Within 60 minutes'), ('5', 'Non-urgent - Within 2 hours')], max_length=1)),
                ('symptoms', models.TextField(help_text='Current symptoms')),
                ('onset', models.CharField(help_text='When did symptoms start?', max_length=100)),
                ('duration', models.CharField(help_text='How long have symptoms persisted?', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='patients.patient')),
                ('triaged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triage_date'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('assessment_type', models.CharField(choices=[('first_visit', 'First Visit Assessment'), ('follow_up', 'Follow-up Assessment')], max_length=20)),
                ('department', models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('nutrition', 'Nutrition'), ('general', 'General Medicine')], max_length=20)),
                ('chief_complaint', models.TextField(help_text='Primary reason for visit')),
                ('history_of_present_illness', models.TextField(help_text='Detailed history of current condition')),
                ('physical_examination', models.TextField(help_text='Physical examination findings')),
                ('mobility_status', models.CharField(blank=True, max_length=100)),
                ('mental_status', models.CharField(blank=True, max_length=100)),
                ('diagnosis', models.TextField(help_text='Clinical diagnosis or impression')),
                ('treatment_plan', models.TextField(help_text='Recommended treatment plan')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.patient')),
                ('related_triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='patients.triage')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
    ]
