# Generated by Django 4.2.7 on 2025-10-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_assessment_related_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='anthropometric_measurements',
            field=models.TextField(blank=True, help_text='Body measurements and composition'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='biochemical_data',
            field=models.TextField(blank=True, help_text='Laboratory values related to nutrition'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='clinical_signs',
            field=models.TextField(blank=True, help_text='Physical signs of nutritional status'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='dietary_history',
            field=models.TextField(blank=True, help_text='Dietary intake patterns and history'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='food_allergies_intolerances',
            field=models.TextField(blank=True, help_text='Food allergies and intolerances'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='functional_assessment',
            field=models.TextField(blank=True, help_text='Functional limitations and ADLs'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='muscle_strength',
            field=models.TextField(blank=True, help_text='Muscle strength testing results'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='nutritional_goals',
            field=models.TextField(blank=True, help_text='Nutritional objectives and targets'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pain_location',
            field=models.TextField(blank=True, help_text='Location and description of pain'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='posture_analysis',
            field=models.TextField(blank=True, help_text='Postural assessment findings'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='range_of_motion',
            field=models.TextField(blank=True, help_text='ROM measurements'),
        ),
    ]
