# Generated by Django 4.2.7 on 2025-10-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_assessment_anthropometric_measurements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Clinical diagnosis or impression'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Recommended treatment plan'),
        ),
    ]
