# Generated by Django 4.2.7 on 2025-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_assessment_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='anthropometric_measurements',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='biochemical_data',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='clinical_signs',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='dietary_history',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='food_allergies_intolerances',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='functional_assessment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='muscle_strength',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='nutritional_goals',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='pain_location',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='posture_analysis',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='range_of_motion',
        ),
        migrations.AddField(
            model_name='assessment',
            name='additional_findings',
            field=models.TextField(blank=True, help_text='Any additional clinical observations'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='department',
            field=models.CharField(blank=True, default='general', max_length=20),
        ),
    ]
