# Generated by Django 4.2.7 on 2026-03-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_simplify_assessment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='cardiovascular',
            field=models.CharField(blank=True, default='', help_text='Cardiovascular exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='chest_xray',
            field=models.CharField(blank=True, default='', help_text='Chest X-Ray findings', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='cns',
            field=models.CharField(blank=True, default='', help_text='CNS exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='deformities',
            field=models.CharField(blank=True, default='', help_text='Deformities', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='ears_lt',
            field=models.CharField(blank=True, default='', help_text='Left ear exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='ears_rt',
            field=models.CharField(blank=True, default='', help_text='Right ear exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='extremities',
            field=models.CharField(blank=True, default='', help_text='Extremities exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='eyes_lt',
            field=models.CharField(blank=True, default='', help_text='Left eye exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='eyes_rt',
            field=models.CharField(blank=True, default='', help_text='Right eye exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='gi_abdomen',
            field=models.CharField(blank=True, default='', help_text='GI/Abdomen exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='heart',
            field=models.CharField(blank=True, default='', help_text='Heart exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='hernia',
            field=models.CharField(blank=True, default='', help_text='Hernia exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='lungs',
            field=models.CharField(blank=True, default='', help_text='Lungs exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='psychiatry',
            field=models.CharField(blank=True, default='', help_text='Psychiatry exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='respiratory_exam',
            field=models.CharField(blank=True, default='', help_text='Respiratory exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='skin',
            field=models.CharField(blank=True, default='', help_text='Skin exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='varicose_veins',
            field=models.CharField(blank=True, default='', help_text='Varicose veins exam', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='venereal_diseases',
            field=models.CharField(blank=True, default='', help_text='Venereal diseases exam', max_length=100),
        ),
    ]
