# Generated by Django 4.2.7 on 2026-03-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_vitalsigns_cardiovascular_vitalsigns_chest_xray_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Group',
                'verbose_name_plural': 'Patient Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_group',
            field=models.ForeignKey(blank=True, help_text='Assign patient to a group for differential pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.patientgroup'),
        ),
    ]
