# Generated by Django 4.2.7 on 2026-03-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientgroup_patient_patient_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='blood_haemoglobin',
            field=models.CharField(blank=True, default='', help_text='Haemoglobin', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='blood_malaria',
            field=models.CharField(blank=True, default='', help_text='Thick film Malaria', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='blood_micro_filaria',
            field=models.CharField(blank=True, default='', help_text='Micro Filaria', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='chemistry_fbs',
            field=models.CharField(blank=True, default='', help_text='F.B.S (Fasting Blood Sugar)', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='chemistry_kfts',
            field=models.CharField(blank=True, default='', help_text='KFTS (Kidney Function Tests)', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='chemistry_lfts',
            field=models.CharField(blank=True, default='', help_text='L.F.T.S (Liver Function Tests)', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='elisa_hbs_ag',
            field=models.CharField(blank=True, default='', help_text='Hbs Ag', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='elisa_hcv_ab',
            field=models.CharField(blank=True, default='', help_text='HCV Ab', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='elisa_hiv',
            field=models.CharField(blank=True, default='', help_text='HIV 1/2 Test', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='other_blood_group',
            field=models.CharField(blank=True, default='', help_text='Blood Group', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='other_pregnancy_test',
            field=models.CharField(blank=True, default='', help_text='Pregnancy Test', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='other_vdrl_tpha',
            field=models.CharField(blank=True, default='', help_text='VDRL / TPHA', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='stool_bilharziasis',
            field=models.CharField(blank=True, default='', help_text='Stool Bilharziasis', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='stool_culture_salmonella',
            field=models.CharField(blank=True, default='', help_text='Culture Salmonella/Shigella', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='stool_giardia',
            field=models.CharField(blank=True, default='', help_text='Stool Giardia', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='stool_helminthes',
            field=models.CharField(blank=True, default='', help_text='Stool Helminthes', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='stool_v_cholerae',
            field=models.CharField(blank=True, default='', help_text='V. Cholerae', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='urine_albumin',
            field=models.CharField(blank=True, default='', help_text='Urine Albumin', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='urine_bilharziasis',
            field=models.CharField(blank=True, default='', help_text='Urine Bilharziasis', max_length=100),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='urine_sugar',
            field=models.CharField(blank=True, default='', help_text='Urine Sugar', max_length=100),
        ),
    ]
