# Generated by Django 4.2.7 on 2026-03-03 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0011_vitalsigns_blood_haemoglobin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='blood_haemoglobin',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='blood_malaria',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='blood_micro_filaria',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='chemistry_fbs',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='chemistry_kfts',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='chemistry_lfts',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='elisa_hbs_ag',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='elisa_hcv_ab',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='elisa_hiv',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='other_blood_group',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='other_pregnancy_test',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='other_vdrl_tpha',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='stool_bilharziasis',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='stool_culture_salmonella',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='stool_giardia',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='stool_helminthes',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='stool_v_cholerae',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='urine_albumin',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='urine_bilharziasis',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='urine_sugar',
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('urine_sugar', models.CharField(blank=True, default='', help_text='Urine Sugar', max_length=100)),
                ('urine_albumin', models.CharField(blank=True, default='', help_text='Urine Albumin', max_length=100)),
                ('urine_bilharziasis', models.CharField(blank=True, default='', help_text='Urine Bilharziasis', max_length=100)),
                ('stool_helminthes', models.CharField(blank=True, default='', help_text='Stool Helminthes', max_length=100)),
                ('stool_giardia', models.CharField(blank=True, default='', help_text='Stool Giardia', max_length=100)),
                ('stool_bilharziasis', models.CharField(blank=True, default='', help_text='Stool Bilharziasis', max_length=100)),
                ('stool_culture_salmonella', models.CharField(blank=True, default='', help_text='Culture Salmonella/Shigella', max_length=100)),
                ('stool_v_cholerae', models.CharField(blank=True, default='', help_text='V. Cholerae', max_length=100)),
                ('blood_haemoglobin', models.CharField(blank=True, default='', help_text='Haemoglobin', max_length=100)),
                ('blood_malaria', models.CharField(blank=True, default='', help_text='Thick film Malaria', max_length=100)),
                ('blood_micro_filaria', models.CharField(blank=True, default='', help_text='Micro Filaria', max_length=100)),
                ('chemistry_fbs', models.CharField(blank=True, default='', help_text='F.B.S (Fasting Blood Sugar)', max_length=100)),
                ('chemistry_lfts', models.CharField(blank=True, default='', help_text='L.F.T.S (Liver Function Tests)', max_length=100)),
                ('chemistry_kfts', models.CharField(blank=True, default='', help_text='KFTS (Kidney Function Tests)', max_length=100)),
                ('elisa_hcv_ab', models.CharField(blank=True, default='', help_text='HCV Ab', max_length=100)),
                ('elisa_hbs_ag', models.CharField(blank=True, default='', help_text='Hbs Ag', max_length=100)),
                ('elisa_hiv', models.CharField(blank=True, default='', help_text='HIV 1/2 Test', max_length=100)),
                ('other_blood_group', models.CharField(blank=True, default='', help_text='Blood Group', max_length=100)),
                ('other_pregnancy_test', models.CharField(blank=True, default='', help_text='Pregnancy Test', max_length=100)),
                ('other_vdrl_tpha', models.CharField(blank=True, default='', help_text='VDRL / TPHA', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional laboratory notes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratory Test',
                'verbose_name_plural': 'Laboratory Tests',
                'ordering': ['-recorded_date'],
            },
        ),
    ]
