# Generated by Django 4.2.7 on 2026-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_vitalsigns_blood_haemoglobin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, help_text='Identification document number', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'National ID'), ('DRIVERS', "Driver's License"), ('PASSPORT', 'Passport'), ('VOTER', "Voter's ID"), ('OTHER', 'Other')], help_text='Type of identification document', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='reason_for_visit',
            field=models.CharField(blank=True, choices=[('CONSULTATION', 'General Consultation'), ('CHECKUP', 'Routine Checkup'), ('EMERGENCY', 'Emergency'), ('FOLLOWUP', 'Follow-up Visit'), ('REFERRAL', 'Referral'), ('TREATMENT', 'Treatment'), ('SCREENING', 'Screening'), ('OTHER', 'Other')], help_text='Reason for current visit', max_length=20),
        ),
    ]
