# Generated by Django 4.2.7 on 2026-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patient_id_number_patient_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_contact',
            field=models.CharField(blank=True, help_text='Phone or email of the referring doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_location',
            field=models.CharField(blank=True, help_text='Location / clinic of the referring doctor', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_name',
            field=models.CharField(blank=True, help_text='Name of the referring doctor', max_length=100),
        ),
    ]
