# Generated by Django 4.2.7 on 2026-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_add_referring_doctor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Heart rate (BPM)', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Breaths per minute', null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
