# Generated by Django 4.2.7 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_vitalsigns_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgroup',
            name='category',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('insurance', 'Insurance'), ('vip', 'VIP'), ('walk_in', 'Walk-in'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
