# Generated by Django 4.2.7 on 2026-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('patients', '0016_patientgroup_category_patientgroup_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='patientgroup',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_groups', to='tenants.hospital'),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='patientgroup',
            unique_together={('hospital', 'name')},
        ),
        migrations.RemoveField(
            model_name='patientgroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='patientgroup',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='patientgroup',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='patientgroup',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='patientgroup',
            name='contact_phone',
        ),
    ]
