# Generated by Django 4.2.20 on 2026-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_hospital_patientgroup_hospital_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='patientgroup',
            name='hospital',
        ),
    ]
